version: '3'
services:
  db:
    image: postgres:alpine3.17
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
    - 5432:5432

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: